title: InStore - Downloader for Instagram
description: Changelog for all releases of InStore, Story Downloader, Collage Photo Grid & Collage Maker Go
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman